train:
  descriptor: hog
  classifier: svm
  outfile: models/svm.pkl
  positive_image_directory: C:/Users/kenan/Desktop/repos/tl-dev/positives/
  negative_image_directory: C:/Users/kenan/Desktop/repos/tl-dev/negatives/
  window_size: (32, 64)

run:
  descriptor: hog
  classifier_location: models/svm.pkl
  detector: spotlight
  heatmap_memory: 12
  heatmap_threshold: 3
  image_directory: D:/tl_data/LISA/dayTest/
  window_size: (32, 64)

svm:
  C: 10.0

hog:
  block_size: (2, 2)
  cell_size: (8, 8)
  orientations: 9

lbp:
  radius: 3
  points: 24

haar:
  row_coordinate:
  column_coordinate:

spotlight_detector:
  threshold: 65
  max_size: 300
  kernel_size: 11

color_detector: